server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: eureka-register

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
#    service-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
