spring:
  application:
    name: spring-cloud-eureka-server
#  security:
#    user:
#      name: admin
#      password: 123456

server:
  port: 8012
#  servlet:
#    context-path: /register

# Eureka相关配置
eureka:
#  server:
#    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/
