#spring:
#  cloud:
#    config:
#      name: spring-cloud-sample-two
#      uri: http://localhost:8014

spring:
  application:
    name: spring-cloud-sample-two

server:
  port: 8014

# Eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8012/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
